name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo chmod +x scripts/check_dependencies.sh
        sudo ./scripts/check_dependencies.sh

    - name: Configure CMake
      run: cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    # Tests are disabled for now
    # - name: Test
    #   working-directory: build
    #   run: ctest -C Release --output-on-failure
