name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        sudo chmod +x scripts/check_dependencies.sh
        sudo ./scripts/check_dependencies.sh
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
    
    - name: Build
      run: |
        cd build
        ninja
    
    # Tests are disabled for now
    # - name: Run Tests
    #   run: |
    #     cd build
    #     ctest --output-on-failure
    
    - name: Create Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd build
        ninja package
    
    - name: Upload Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: ally-mc-launcher
        path: build/ally-mc-launcher-*.deb