name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies
      run: |
        sudo chmod +x scripts/setup_prerequisites.sh
        sudo ./scripts/setup_prerequisites.sh
    
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -GNinja ..
    
    - name: Build
      run: |
        cd build
        ninja
    
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure
    
    - name: Create Package
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        cd build
        ninja package
    
    - name: Upload Artifact
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: ally-mc-launcher
        path: build/ally-mc-launcher-*.deb